### ISSUE TITLE
Upgrade the major version of react-scripts and related tooling

### ISSUE THREAD

**Issue by tuukka** [gatesolve/gatesolve-ui#542]
- [x] Upgrade to React v7 and typescript-eslint v4 (#615)
- [x] Upgrade to eslint-config-prettier v7 (#570)
- [x] Fix service worker for react-scripts v4 (#616)
